name: Update External PRs in README

on:
  schedule:
    - cron: "30 18 * * *"  # Runs daily at 00:00 IST
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch external PRs via GitHub API and update README
        run: |
          echo "Fetching latest external PRs for viralcodex..."
          
          # Fetch latest PRs authored by viralcodex
          data=$(curl -s "https://api.github.com/search/issues?q=is:pr+author:viralcodex&sort=created&order=desc&per_page=20")

          # Build Markdown table header
          table="| Repository | Title | Status |\n|-------------|--------|---------|"

          # Extract and append rows for PRs not belonging to viralcodex
          echo "$data" | jq -r '
            .items[]
            | select(.repository_url | contains("viralcodex") | not)
            | "| [" + (.repository_url | split("/")[-1]) + "](https://github.com/" + (.repository_url | split("/")[-2] + "/" + .repository_url | split("/")[-1]) + ")"
              + " | [" + (.title | gsub("\\|"; "/")) + "](" + .html_url + ")"
              + " | " + if .state == "open" then "🟢 Open" else (if .pull_request.merged_at then "🟣 Merged" else "🔴 Closed" end) end + " |"
          ' | head -n 10 >> table.md

          # If no external PRs found, set a placeholder
          if [ ! -s table.md ]; then
            echo "| – | No recent external PRs found | – |" > table.md
          fi

          # Merge header and table
          echo -e "$table\n$(cat table.md)" > pr_table.md
          rm -f table.md

          # Replace section in README.md
          awk -v content="$(cat pr_table.md)" '
            BEGIN { start=0 }
            /<!--START_SECTION:external_prs-->/ { print; print content; start=1; next }
            /<!--END_SECTION:external_prs-->/ { start=0 }
            !start
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "update: external PRs table"
          git push
