name: Update External PRs in README

on:
  schedule:
    - cron: "30 18 * * *"  # Runs every day at 18:30 UTC = 00:00 IST
  workflow_dispatch:        # Allows manual trigger from Actions tab

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch external PRs via GitHub API and update README
        run: |
          echo "Fetching PRs for viralcodex..."

          prs=$(curl -s "https://api.github.com/search/issues?q=is:pr+author:viralcodex" \
            | jq -r '
              `| Title | Repository | Status |, |:-------:|:-------------:|:--------:`,
              (.items[]
                | select(.repository_url | contains("viralcodex") | not)
                | "| [" + .title + "](" + .html_url + ") | `"
                  + ((.repository_url | split("/")[-2]) + "/" + (.repository_url | split("/")[-1])) + "` | "
                  + (if .state == "closed" then
                        (if (.pull_request.merged_at != null) then "merged" else "closed" end)
                     else
                        "open"
                     end)
                  + " |"
              )
            ' | head -n 12)

          if [ -z "$prs" ]; then
            prs="| Title | Repository | Status |
                 |-------|-------------|--------|
                 | No recent external PRs found. | - | - |"
          fi

          echo "Updating README..."

          awk -v content="$prs" '
            BEGIN { start=0 }
            /<!--START_SECTION:external_prs-->/ { print; print content; start=1; next }
            /<!--END_SECTION:external_prs-->/ { start=0 }
            !start
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "update: external PRs list"
          git push
